baseURL = 'https://sruja.ai/'
languageCode = 'en-us'
# title = 'Sruja Documentation'


[module]
  [[module.imports]]
    path = 'github.com/alex-shpak/hugo-book'

[menu]
  [[menu.main]]
    name = 'Courses'
    url = '/courses/'
    weight = 1
  [[menu.main]]
    name = 'Resources'
    url = '/resources/'
    weight = 2
  [[menu.main]]
    name = 'Docs'
    url = '/docs/'
    weight = 3
  [[menu.main]]
    name = 'Blogs'
    url = '/blogs/'
    weight = 4
  [[menu.main]]
    name = 'Tutorials'
    url = '/tutorials/'
    weight = 5
  [[menu.main]]
    name = 'Community'
    url = '/community/'
    weight = 6
  [[menu.main]]
    name = 'GitHub'
    url = 'https://github.com/sruja-ai/sruja'
    weight = 7

[params]
  BookTheme = 'auto'
  BookSection = '*'
  # BookLogo = 'sruja-logo.svg'
  BookFavicon = '/sruja-logo.svg'
  BookMenuBundle = '/menu'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
