baseURL = 'https://sruja.ai/'
languageCode = 'en-us'
title = 'Sruja Documentation'


[module]
  [[module.imports]]
    path = 'github.com/alex-shpak/hugo-book'

[menu]
  [[menu.main]]
    name = 'Docs'
    url = '/docs/'
    weight = 1
  [[menu.main]]
    name = 'Blog'
    url = '/blog/'
    weight = 2
  [[menu.main]]
    name = 'Tutorials'
    url = '/tutorials/'
    weight = 3
  [[menu.main]]
    name = 'GitHub'
    url = 'https://github.com/sruja-ai/sruja'
    weight = 4

[params]
  BookTheme = 'auto'
  BookSection = '*'
  BookLogo = 'sruja-logo.svg'
  BookFavicon = 'sruja-logo.svg'
  BookMenuBundle = '/menu'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
